[build-system]
requires = ["setuptools>=75.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "noaaplotter_streamlit"
version = "0.0.10"
description = "This is a Streamlit app utilizing the noaaplotter package"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "jupyterlab",
    "ipython",
    "noaaplotter @ git+https://github.com/initze/noaaplotter.git@v052_dev"
]

[tool.setuptools.packages.find]
where = ["src"]
